import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read = path => readFileSync(new URL(`../../${path}`, import.meta.url),'utf8');
const home=read('src/pages/index.astro'),flow=read('src/pages/flow.astro');
assert.doesNotMatch(home+flow,/FlowIdeasPitStop|HomeRaceCapabilityAct|FlowRaceBlueprint|home-variants/);
assert.doesNotMatch(read('src/components/Nav.astro'),/theme-toggle|lockedTheme|data-theme-lock|of-theme/);
const homeSections=['HomeHero','CapabilityRibbon','HomeContinuity','HomeDocumentWorkshop','HomeIdeas','HomeProof','Founder','EssayInvitation','Ecosystem','HomeClosing'];
const positions=homeSections.map(name=>home.indexOf(`<${name} />`));
assert.ok(positions.every(i=>i>=0));assert.deepEqual([...positions].sort((a,b)=>a-b),positions);
for(const name of ['FlowRhythm','FlowDocuments','FlowIdeas','FlowRouting','FlowReceipts','FlowMorningBriefing','FlowEverydayCraft','FlowLibrary','FlowPlans','FlowFaq'])assert.ok(flow.includes(`<${name} />`));
const concept=read('src/pages/flow/ideas-in-motion.astro');
assert.match(concept,/if \(!ORIONFOLD_FLOW_IDEAS_CAMPAIGN\)/,'historical concept remains gated');
assert.match(concept,/noindex=\{true\}/);
assert.match(read('astro.config.mjs'),/!page\.endsWith\(['"]\/flow\/ideas-in-motion\/['"]\)/);
const measurements=read('src/data/flow-measurements.ts');
for(const fact of ['22.3 ms','$0.00425','1.1 s','7 actions'])assert.ok(measurements.includes(fact));
assert.match(read('src/components/living/FlowPlans.astro'),/FLOW\.monthly\.amount/);
assert.match(read('src/components/living/FlowPlans.astro'),/FLOW\.annual\.amount/);
console.log('Living Systems arc: approved section order, measured evidence, gated historical campaign');
