import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read = path => readFileSync(new URL(`../../${path}`, import.meta.url),'utf8');
const page=read('src/pages/index.astro'), hero=read('src/components/living/HomeHero.astro');
const demo=read('src/components/living/HomeKnowledgeDemo.astro'), css=read('src/styles/living-base.css')+read('src/styles/living-home.css');
assert.match(page, /<HomeHero \/>/);
assert.match(hero, /MAKE[\s\S]*KNOWLEDGE[\s\S]*LIVING[\s\S]*THING/);
assert.match(hero, /<HomeKnowledgeDemo \/>/);
assert.match(hero, /<picture[\s\S]*hero-home-paper-planes\.webp/);
assert.doesNotMatch(page+hero, /FlowShot|pit-stop-daylight|FlowRaceBlueprint|<video/);
for(const control of ['data-demo-next','data-demo-replay','data-demo-keep','data-demo-revert'])assert.ok(demo.includes(control),`${control} remains operable`);
assert.match(demo,/data-demo-state/);
assert.match(demo,/data-knowledge-graph/, 'homepage renders a knowledge diagram');
assert.doesNotMatch(demo,/ls-mini-chart/, 'homepage no longer duplicates the Flow bar chart');
assert.match(read('src/components/living/FlowHero.astro'), /<ProductDemo \/>/, 'Flow keeps its existing product illustration');
assert.match(demo, /src="\/logos\/orionfold-mark-3d-32\.png"/, 'native mock reuses the shared small brand mark');
assert.doesNotMatch(demo, /living-systems\/orionfold-mark\.png/, 'no duplicate oversized 24px illustration logo');
assert.match(css,/backdrop-filter:/);
assert.match(css,/prefers-reduced-motion/);
assert.match(page,/<ConfirmBanner \/>/);
assert.match(page,/SoftwareApplication/);
assert.match(read('src/data/og.ts'), /ogVersion\(p\)/, 'social URLs remain content-versioned');
assert.match(read('src/lib/og/card.ts'),/hasShot \? 560 : 900/, 'other shot-based cards still reserve room for their screenshots');
console.log('home hero: approved origami, native interactive mock, metadata and confirmation seams');
